"""adding units with relationship to users

Revision ID: 29fa40098649
Revises: 53acb8cb160b
Create Date: 2023-04-09 11:52:40.574105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fa40098649'
down_revision = '53acb8cb160b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
