"""adding units with relationship to users

Revision ID: 53acb8cb160b
Revises: 
Create Date: 2023-04-09 11:51:01.966504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53acb8cb160b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employments',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('years_active', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['Units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employments')
    op.drop_table('Users')
    op.drop_table('Units')
    # ### end Alembic commands ###
