"""relationship table to reflect years active

Revision ID: 9f1713c5b49f
Revises: caca28e271d7
Create Date: 2023-04-09 19:53:10.135530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1713c5b49f'
down_revision = 'caca28e271d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
