"""relationship table to reflect years active

Revision ID: f001f6d7ccbc
Revises: 9f1713c5b49f
Create Date: 2023-04-09 20:02:48.706106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f001f6d7ccbc'
down_revision = '9f1713c5b49f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
